# Generated by Django 5.0.1 on 2024-04-13 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume_revive", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedfile",
            name="job_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="uploadedfile",
            name="file",
            field=models.FileField(upload_to="uploads/%Y/%m/%d"),
        ),
    ]
