# Generated by Django 5.0.1 on 2024-04-13 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume_revive", "0002_uploadedfile_job_description_alter_uploadedfile_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedfile",
            name="ats_score",
            field=models.FloatField(default=0.0),
        ),
    ]
