# Generated by Django 5.0.1 on 2024-04-29 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume_revive", "0004_remove_uploadedfile_ats_score_uploadedfile_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadedfile",
            name="file",
            field=models.FileField(upload_to="uploads/%Y/%m"),
        ),
    ]
